[package]
name = "crusty"
version = "0.1.0"
authors = ["Wolf Vollprecht <w.vollprecht@gmail.com>"]
edition = "2018"

[dependencies]
libsolv = { git = "https://github.com/ignatenkobrain/libsolv-rs" }
reqwest = "*"
serde = "*"
serde_json = "1.0"
libc = "0.2.43"  # Same as rust-libc-devel package
